//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioREST.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaComputadoresEntities : DbContext
    {
        public VentaComputadoresEntities()
            : base("name=VentaComputadoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agencia> Agencia { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }

        [JsonIgnore]
        public virtual DbSet<Computador> Computador { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoComputador> TipoComputador { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}
