//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal Precio { get; set; }
        public string Nit { get; set; }
        public Nullable<int> IdComputador { get; set; }
        public Nullable<int> Documento { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Computador Computador { get; set; }
    }
}
